linters:
  enable:
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
  disable:
    - errcheck  # Disable errcheck for now due to many legacy issues
    - gocritic
    - gosec
    - lll
    - unparam

issues:
  exclude-rules:
    # Skip generated files
    - path: ".*\\.gen\\.go"
      linters:
        - typecheck
        - unused
    - path: "internal/reporter/graphql/generated/"
      linters:
        - typecheck
        - unused
        - staticcheck
    # Skip GraphQL generated code issues
    - path: "internal/reporter/graphql/generated/generated.go"
      linters:
        - typecheck
    # Skip JWT undefined issues (false positive)
    - path: "pkg/middleware/auth.go"
      text: "undefined: jwt"
      linters:
        - typecheck
    # Skip unused helper functions in GraphQL resolvers
    - path: "internal/reporter/graphql/.*"
      linters:
        - unused
    # Skip staticcheck for known pre-existing issues
    - linters:
        - staticcheck
      text: "SA1019.*deprecated"
    - linters:
        - staticcheck
      text: "SA1029.*should not use built-in type string as key"
    - linters:
        - staticcheck
      text: "SA9003.*empty branch"
    # Skip gofmt for known pre-existing formatting issues
    - path: "internal/domains/analytics/.*"
      linters:
        - gofmt
  exclude:
    - "undefined: jwt"
    - "ec.Recover undefined"
    - "ec.Variables undefined"
    - "missing return"
    - "func.*is unused"
    - "File is not properly formatted"

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - internal/domains/tags/mocks
  issues:
    exclude-dirs:
      - vendor
    exclude-files:
      - ".*\\.gen\\.go"
      - "internal/reporter/graphql/generated/generated.go"