name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR Title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
        requireScope: false
        subjectPattern: ^(?![A-Z]).+$
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}"
          didn't match the configured pattern. Please ensure that the subject
          doesn't start with an uppercase character.

  check-acceptance-tests:
    runs-on: ubuntu-latest
    needs: validate-pr
    steps:
    - uses: actions/checkout@v4
    
    - name: Run acceptance tests with Dagger
      uses: dagger/dagger-for-github@8.0.0
      with:
        verb: call
        module: ./ci
        args: acceptance-test --source .
      continue-on-error: true
      
    - name: Comment PR
      uses: actions/github-script@v7
      if: failure()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '⚠️ Acceptance tests failed. Please check the logs and fix any issues.'
          })